backend:
  name: github
  repo: reddynew/legal_next
  branch: main

  base_url: "http://localhost:3001"
  auth_endpoint: "auth/api/decap"

publish_mode: simple

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: blog
    label: Blog Posts
    folder: "app/blog/content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Description, name: description, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown }
